//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanicilar
    {
        public int C1 { get; set; }
        [Required(ErrorMessage ="Lütfen kullanıcı adınızı giriniz")]
        public string kad { get; set; }
        [Required(ErrorMessage = "Lütfen parolanızı giriniz")]
        public string sifre { get; set; }
        public Nullable<sbyte> role { get; set; }

        public virtual bool BeniHatirla { get; set; }
    }
}
